name: Code Coverage

on:
  push:
    branches:
    - main
    
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      # check out code
      - name: Checkout Code
        uses: actions/checkout@v6
      # step 2 set up python
      - name: "Setup Python"
        uses: actions/setup-python@v6
        with:
          python-version: '3.13t'

      # step 3
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      # step 4
      - name: Run tests
        run: |
          pytest --cov=py_tools --cov-report xml
      # step 5
      - name: Upload Report
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{secrets.GITHUB_TOKEN}}